# Generated by Django 5.0.6 on 2025-03-03 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recettes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recettes_commentaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recette',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recettes_commentaires', to='recettes.recette'),
        ),
    ]
